apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: og33cr9o4-nodejs
  janus-idp.io/tekton: og33cr9o4-nodejs
  backstage.io/kubernetes-id: og33cr9o4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: og33cr9o4-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
